[connections.teleco]
    type="sql"
    dialect="postgresql"
    username="postgres"
    password="1234"
    host="db" # IP or URL
    port= 5432 # Port number
    database="xdr_data" # Database name

 